# Generated by Django 4.1.3 on 2022-11-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeassessment',
            name='completed_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
